services:
  - type: web
    name: valura-ai-dashboard
    runtime: docker
    repo: https://github.com/AyushYele25/Valura_AI.git
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 7860
      - key: BOOK_PATH
        value: client_book.json
      - key: MARKET_PATH
        value: market_data.json
